### ISSUE TITLE
Error: undefined method `exists?' for class File

### ISSUE THREAD

**Issue by NickVulkers** [dockergiant/homebrew-roll#1]
Error when trying to run `brew upgrade`:
```
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Upgrading 1 outdated package:
dockergiant/roll/roll 0.2.6.3 -> 0.2.6.4
Error: undefined method `exists?' for class File
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Taps/dockergiant/homebrew-roll/Formula/roll.rb:35:in `docker_installed?'
/opt/homebrew/Library/Taps/dockergiant/homebrew-roll/Formula/roll.rb:18:in `has_docker?'
/opt/homebrew/Library/Taps/dockergiant/homebrew-roll/Formula/roll.rb:7:in `block in <class:DockerRequirement>'
/opt/homebrew/Library/Homebrew/requirement.rb:77:in `instance_eval'
/opt/homebrew/Library/Homebrew/requirement.rb:77:in `block in satisfied?'
/opt/homebrew/Library/Homebrew/requirement.rb:225:in `yielder'
/opt/homebrew/Library/Homebrew/requirement.rb:76:in `satisfied?'
/opt/homebrew/Library/Homebrew/formula_installer.rb:588:in `block in expand_requirements'
/opt/homebrew/Library/Homebrew/requirement.rb:269:in `block in prune?'
/opt/homebrew/Library/Homebrew/requirement.rb:267:in `catch'
/opt/homebrew/Library/Homebrew/requirement.rb:267:in `prune?'
/opt/homebrew/Library/Homebrew/requirement.rb:250:in `block (2 levels) in expand'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/set.rb:501:in `each_key'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/set.rb:501:in `each'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/delegate.rb:87:in `method_missing'
/opt/homebrew/Library/Homebrew/requirement.rb:249:in `block in expand'
/opt/homebrew/Library/Homebrew/requirement.rb:248:in `each'
/opt/homebrew/Library/Homebrew/requirement.rb:248:in `expand'
/opt/homebrew/Library/Homebrew/formula.rb:2257:in `recursive_requirements'
/opt/homebrew/Library/Homebrew/formula_installer.rb:578:in `expand_requirements'
/opt/homebrew/Library/Homebrew/formula_installer.rb:525:in `compute_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:231:in `verify_deps_exist'
/opt/homebrew/Library/Homebrew/formula_installer.rb:218:in `prelude'
/opt/homebrew/Library/Homebrew/upgrade.rb:73:in `block in upgrade_formulae'
/opt/homebrew/Library/Homebrew/upgrade.rb:54:in `each'
/opt/homebrew/Library/Homebrew/upgrade.rb:54:in `filter_map'
/opt/homebrew/Library/Homebrew/upgrade.rb:54:in `upgrade_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:220:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```
Setup hasn't changed since the last update, still using [Orbstack](https://orbstack.dev/).

**Comment by marcepartment** [comment]
Getting the same here

**Comment by rbouma2** [comment]
@NickVulkers It has been fixed!
